/* tslint:disable */
/* eslint-disable */

/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BrightnessModel
 */
export interface BrightnessModel {
    /**
     *
     * @type {number}
     * @memberof BrightnessModel
     */
    value: any;
    /**
     *
     * @type {number}
     * @memberof BrightnessModel
     */
    duration: any;
    /**
     *
     * @type {string}
     * @memberof BrightnessModel
     */
    effect: BrightnessModelEffectEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BrightnessModelEffectEnum {
    Sudden = 'sudden',
    Smooth = 'smooth'
}

