/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LightDataModel
 */
export interface LightDataModel {
    /**
     * 
     * @type {number}
     * @memberof LightDataModel
     */
    brightness: any;
    /**
     * 
     * @type {ColorRgbModel}
     * @memberof LightDataModel
     */
    color: any;
    /**
     * 
     * @type {boolean}
     * @memberof LightDataModel
     */
    connected: any;
    /**
     * 
     * @type {number}
     * @memberof LightDataModel
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof LightDataModel
     */
    ip: any;
    /**
     * 
     * @type {number}
     * @memberof LightDataModel
     */
    mode: any;
    /**
     * 
     * @type {string}
     * @memberof LightDataModel
     */
    name: any;
    /**
     * 
     * @type {number}
     * @memberof LightDataModel
     */
    port: any;
    /**
     * 
     * @type {boolean}
     * @memberof LightDataModel
     */
    powered: any;
    /**
     * 
     * @type {string}
     * @memberof LightDataModel
     */
    room: LightDataModelRoomEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum LightDataModelRoomEnum {
    LivingRoom = 'living room',
    Chambers = 'chambers',
    Others = 'others'
}

