/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PresetModel
 */
export interface PresetModel {
    /**
     *
     * @type {string}
     * @memberof PresetModel
     */
    key: any;
    /**
     *
     * @type {string}
     * @memberof PresetModel
     */
    color: any;
}
