/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccessPoint
 */
export interface AccessPoint {
    /**
     * 
     * @type {string}
     * @memberof AccessPoint
     */
    mac?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessPoint
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessPoint
     */
    connectivityType?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessPoint
     */
    uid?: any;
    /**
     * 
     * @type {WifiInformation}
     * @memberof AccessPoint
     */
    wifiInformation?: any;
    /**
     * 
     * @type {number}
     * @memberof AccessPoint
     */
    rxRate?: any;
    /**
     * 
     * @type {number}
     * @memberof AccessPoint
     */
    txRate?: any;
}
