/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Flags
 */
export interface Flags {
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    vht?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    legacy?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    authorized?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    ht?: any;
}
