/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Last
 */
export interface Last {
    /**
     * 
     * @type {number}
     * @memberof Last
     */
    bitrate?: any;
    /**
     * 
     * @type {number}
     * @memberof Last
     */
    mcs?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Last
     */
    shortgi?: any;
    /**
     * 
     * @type {number}
     * @memberof Last
     */
    vhtMcs?: any;
    /**
     * 
     * @type {string}
     * @memberof Last
     */
    width?: any;
}
