version: "3"
services:
  #  app:
  #    image: elyspio/light-manager
  #    volumes:
  #      - ./app/logs:/app/logs
  #      - ./app/conf.json:/front/conf.json
  #    ports:
  #      - "1982:1982/udp"
  #    environment:
  #      BACKEND_PORT: ${PRIVATE_PORT}
  #      DATABASE_PORT: ${DATABASE_PORT}
  #      DATABASE_URL: ${DATABASE_URL}
  #      DATABASE_USER: ${DATABASE_USER}
  #      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #      DATABASE_DATABASE: ${DATABASE_DATABASE}
  #      NETWORK_INTERFACE: eth0
  #    network_mode: "host"
  #    container_name: light-manager-app
  #    restart: always

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DATABASE}
    volumes:
      - "./database:/var/lib/postgresql/data"
    ports:
      - ${DATABASE_PORT}:5432
    container_name: light-manager-db
