/* tslint:disable */
/* eslint-disable */

/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostLoginModel
 */
export interface PostLoginModel {
    /**
     *
     * @type {string}
     * @memberof PostLoginModel
     */
    token?: any;
    /**
     *
     * @type {string}
     * @memberof PostLoginModel
     */
    comment?: any;
}
