/* tslint:disable */
/* eslint-disable */

/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostLoginRequest
 */
export interface PostLoginRequest {
    /**
     *
     * @type {string}
     * @memberof PostLoginRequest
     */
    hash?: any;
    /**
     *
     * @type {string}
     * @memberof PostLoginRequest
     */
    name?: any;
}
